# Generated by Django 3.1 on 2020-08-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200816_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineintake',
            name='quantity',
            field=models.CharField(choices=[('1', 'One Time'), ('2', 'Two Time'), ('3', 'Three Time')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ManyToManyField(blank=True, null=True, to='patient.Disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.ManyToManyField(blank=True, null=True, to='patient.Prescription'),
        ),
    ]
