# Generated by Django 3.1 on 2020-08-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20200817_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='medicine_intake',
            new_name='prescriptions',
        ),
    ]
